[workspace]
members = [
    "crates/*",
]

resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Paul Hendricks, Rachel Oberman", "Arun Raman"]

[workspace.lints.rust]
warnings = "deny"

[workspace.lints.clippy]
restriction = "deny"
