global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'router-controller-metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets: 
        - 'router-controller:8084'
  - job_name: 'router-server-metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['router-server:8002']
  - job_name: 'locust'
    static_configs:
    - targets: ['locust:4000']